server:
  port: 12004
spring:
  profiles:
    active: dev
  application:
    name: mis-finance
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:11000/eureka/
logging:
  level:
    root: info
