server:
  port: 12001
spring:
  application:
    name: mis-finance
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:11000/eureka/,http://localhost:11001/eureka/,http://localhost:11002/eureka/
logging:
  level:
    root: info
management:
  security:
    enabled: false
info:
  build:
    artifact: "@project.artifactId@"
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"

