server:
  port: 12000
spring:
  application:
    name: mis-finance
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  sleuth:
    sampler:
      percentage: 1.0
#  zipkin:
#    enabled: true
#    base-url: http://localhost:11100
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:11000/eureka/,http://localhost:11001/eureka/,http://localhost:11002/eureka/
logging:
  level:
    root: info
management:
  security:
    enabled: false
info:
  build:
    artifact: "@project.artifactId@"
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"

